In [9]:
#create a two by two array:
import numpy as np
m=np.array([[0,2],[0,2]])
m

array([[0, 2],
       [0, 2]])

In [1]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
import numpy as np
np. arange(0,10,5)


array([0, 5])

In [4]:
#use of linspace
import numpy as np
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [5]:
import numpy as np
np.linspace(0,6,12)

array([0.        , 0.54545455, 1.09090909, 1.63636364, 2.18181818,
       2.72727273, 3.27272727, 3.81818182, 4.36363636, 4.90909091,
       5.45454545, 6.        ])

In [6]:
import numpy as np
np.linspace(0,7,14)

array([0.        , 0.53846154, 1.07692308, 1.61538462, 2.15384615,
       2.69230769, 3.23076923, 3.76923077, 4.30769231, 4.84615385,
       5.38461538, 5.92307692, 6.46153846, 7.        ])

In [22]:
#create an array in numpy
import numpy as np
b=np.array([1,2,3])
b

array([1, 2, 3])

In [23]:
# to know it is ndarray or not
type(b)

numpy.ndarray

In [24]:
# to check its data type
b.dtype

dtype('int32')

In [26]:
# to know its axes and rank
b.ndim

1

In [28]:
# to know its length
b.size

3

In [30]:
# to know its shape
b.shape

(3,)

In [31]:
#Create two dimensional array 2x2
import numpy as np
a=np.array([[1.2, 1.3], [1.4,1.5]])
a

array([[1.2, 1.3],
       [1.4, 1.5]])

In [32]:
a.dtype

dtype('float64')

In [33]:
a.shape

(2, 2)

In [34]:
a.size

4

In [35]:
a.ndim

2

In [36]:
# itemsize attribut tells the size of array in bytes
a.itemsize

8

In [37]:
# data attribute tells the actual elements in array
a.data

In [38]:
# create an array
import numpy as np
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c.dtype

dtype('int32')

In [40]:
c.size

6

In [41]:
c.shape

(2, 3)

In [42]:
c.itemsize

4

In [43]:
c.data

In [44]:
c.ndim

2

In [45]:
# create another array
import numpy as np
d=np.array(((1,2,3),[4,5,6],(7,8,9)))

In [46]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# create another array using tuple
import numpy as np
e=np.array(((1.1,1.2,1.3),(1.4,1.5,1.6),(1.7,1.8,1.9)))

In [48]:
e

array([[1.1, 1.2, 1.3],
       [1.4, 1.5, 1.6],
       [1.7, 1.8, 1.9]])

In [54]:
e.dtype
e.dtype.name

'float64'

In [50]:
# create another data type ndarray
import numpy as np
d=np.array([['a', 'b'],['c','d']])
             

In [51]:
d

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [52]:
d.dtype

dtype('<U1')

In [53]:
d.dtype.name

'str32'

In [55]:
# to create a dtype array
import numpy as np
f=np.array([[1,2,3],[4,5,6]], dtype=complex)

In [56]:
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [57]:

f.dtype

dtype('complex128')

In [58]:
# create intrinsic ndarray
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
#to use arange function
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
import numpy as np
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
# to generate two D array from one D array
import numpy as np
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [1]:
import numpy as np
np.arange(0,72).reshape(8,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

In [2]:
np.arange(0,120).reshape(12,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [ ]:
#linspace() is very similar to arange() function and it display the values in float or can say double

In [3]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
# to generate random number
np.random.random(3)

array([0.39216691, 0.70836822, 0.58136862])

In [5]:
np.random.random((3,3))

array([[0.50199277, 0.64396937, 0.7703415 ],
       [0.70075636, 0.09006083, 0.58851881],
       [0.6335549 , 0.63902977, 0.51187434]])

In [6]:
# Basic arithmatic operation
np.arange(4)

array([0, 1, 2, 3])

In [7]:
import numpy as np
f=np.arange(6)
print(f)

[0 1 2 3 4 5]


In [8]:
f+4

array([4, 5, 6, 7, 8, 9])

In [9]:
f+10

array([10, 11, 12, 13, 14, 15])

In [10]:
f*5

array([ 0,  5, 10, 15, 20, 25])

In [13]:
g=np.arange(6,12)
print(g)

[ 6  7  8  9 10 11]


In [14]:
print(f+g)

[ 6  8 10 12 14 16]


In [15]:
print(f*g)

[ 0  7 16 27 40 55]


In [24]:
import numpy as np
A=np.arange(0,25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
import numpy as np
B=np.arange(0,25).reshape(5,5)
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [28]:
print(A+B)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [31]:
import numpy as np
C=np.zeros((5,5))
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
print(A+C)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [33]:
import numpy as np
D=np.ones((5,5))
print(D)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
print(A*D)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [35]:
np.dot(A,B)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [36]:
# universal function
import numpy as np
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
a=a+1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [39]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [40]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [41]:
# aggregate 
a.sum()

55

In [42]:
a.min()

1

In [43]:
a.max()

10

In [44]:
a.mean()

5.5

In [45]:
a.std()

2.8722813232690143

In [52]:
#indexing
import numpy as np
b=np.arange(10,16)
print(b)

[10 11 12 13 14 15]


In [53]:
b[5]

15

In [54]:
print(b[[1,2,4]])

[11 12 14]


In [62]:
# indexing on two dimensions array
import numpy as np
c=np.arange(0,36).reshape(6,6)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [65]:
c[1,2]

8

In [66]:
c[5,5]

35

In [67]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [69]:
print(a[1:10])

[ 2  3  4  5  6  7  8  9 10]


In [70]:
print(a[3:10])

[ 4  5  6  7  8  9 10]


In [71]:
print(a[1:3:10])

[2]


In [72]:
print(a[::2])

[1 3 5 7 9]


In [73]:
print(a[::3])

[ 1  4  7 10]


In [74]:
print(a[::1])

[ 1  2  3  4  5  6  7  8  9 10]


In [75]:
print(a[1::])

[ 2  3  4  5  6  7  8  9 10]


In [76]:
print(a[2::])

[ 3  4  5  6  7  8  9 10]


In [77]:
print(a[1:2:])

[2]


In [78]:
print(a[1:2:10])

[2]


In [79]:
print(a[1:10:2])

[ 2  4  6  8 10]


In [81]:
import numpy as np
g=np.arange(10,19).reshape(3,3)
print(g)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [82]:
# to extract rows
print(g[0,:])

[10 11 12]


In [84]:
print(g[1,:])

[13 14 15]


In [85]:
print(g[2,:])

[16 17 18]


In [86]:
# to extract columns
print(g[:,0])

[10 13 16]


In [4]:
import numpy as np
h=np.arange(0,12).reshape(4,3)

In [5]:
print(h)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
for i in h:
    print(h)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
for row in h:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [8]:
for column in h:
    print(column)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [9]:
for item in h.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
np.apply_along_axis(np.mean,axis=0,arr=h)

array([4.5, 5.5, 6.5])

In [11]:
np.apply_along_axis(np.mean,axis=1,arr=h)

array([ 1.,  4.,  7., 10.])

In [16]:
np.apply_along_axis(np.mean,axis=0,arr=h)

array([4.5, 5.5, 6.5])

In [21]:
np.apply_along_axis(np.mean,axis=1,arr=h)

array([ 1.,  4.,  7., 10.])

In [22]:
#Condition and Boolean Arrays
# to create 4X4 Matrix containing random numbers between 0 and 1
import numpy as np
V=np.random.random((4,4))
print(V)

[[0.86224883 0.37967261 0.44007805 0.60846736]
 [0.3159967  0.04816498 0.05406551 0.07274955]
 [0.39890356 0.82477331 0.64949655 0.04275176]
 [0.1146584  0.02268321 0.85969206 0.07255891]]


In [23]:
# To apply an operator condition 
# and that will return value a Boolean Array containing true value in the positions in which the condition is satified
V<0.5

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True]])

In [24]:
# To extract all elements smaller than 0.5, so obtain a new array
V[V<0.5]

array([0.37967261, 0.44007805, 0.3159967 , 0.04816498, 0.05406551,
       0.07274955, 0.39890356, 0.04275176, 0.1146584 , 0.02268321,
       0.07255891])

In [26]:
# To create a matrix 5x5 that will contain a boolean arrays
import numpy as np
Z=np.random.random((5,5))
print(Z)

[[0.15028923 0.10849382 0.8654888  0.87408422 0.52077915]
 [0.28563066 0.76006997 0.44704814 0.9711565  0.92177253]
 [0.35679232 0.51716637 0.97676998 0.76736398 0.60017435]
 [0.45545747 0.53321184 0.4477195  0.7646558  0.38763855]
 [0.02861798 0.4955273  0.20126039 0.51730219 0.39535451]]


In [27]:
# To create a matrix 6x6 that will contain a boolean array
import numpy as np
A=np.random.random((7,7))
print(A)

[[0.02583254 0.21322461 0.94093265 0.94888479 0.29617615 0.29293977
  0.32012238]
 [0.36705873 0.87372817 0.37736892 0.2942622  0.18729995 0.61250269
  0.54605265]
 [0.41270229 0.47253475 0.85096157 0.3153031  0.4435217  0.46750818
  0.83435357]
 [0.61586576 0.4868566  0.698486   0.72679074 0.59790595 0.08350983
  0.97724198]
 [0.42811824 0.75070913 0.23743527 0.43882555 0.03966791 0.30511251
  0.86185098]
 [0.10027638 0.49945819 0.11201136 0.77518521 0.16928813 0.26333011
  0.13348796]
 [0.55933087 0.62963317 0.32848533 0.15898177 0.56859268 0.74794436
  0.00923617]]


In [29]:
# To print boolean value
A<0.7

array([[ True,  True, False, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True, False],
       [ True, False,  True,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True]])

In [30]:
# To print value which is 0.7
A[A<0.7]

array([0.02583254, 0.21322461, 0.29617615, 0.29293977, 0.32012238,
       0.36705873, 0.37736892, 0.2942622 , 0.18729995, 0.61250269,
       0.54605265, 0.41270229, 0.47253475, 0.3153031 , 0.4435217 ,
       0.46750818, 0.61586576, 0.4868566 , 0.698486  , 0.59790595,
       0.08350983, 0.42811824, 0.23743527, 0.43882555, 0.03966791,
       0.30511251, 0.10027638, 0.49945819, 0.11201136, 0.16928813,
       0.26333011, 0.13348796, 0.55933087, 0.62963317, 0.32848533,
       0.15898177, 0.56859268, 0.00923617])

In [31]:
# Shape Manipulation
# How to convert one-dimensional array into two-dimensional array
import numpy as np
B=np.random.random((10))
print(B)

[0.27402942 0.66078788 0.34532455 0.571043   0.39601638 0.27276959
 0.53194231 0.6940196  0.14721234 0.43001565]


In [33]:
# to use reshape() function to convert oned d-array into two d-array
C=B.reshape(2,5)
print(C)

[[0.27402942 0.66078788 0.34532455 0.571043   0.39601638]
 [0.27276959 0.53194231 0.6940196  0.14721234 0.43001565]]


In [35]:
import numpy as np
C=np.random.random((16))
print(C)

[0.14848473 0.97824624 0.26593814 0.84206382 0.04942251 0.39308293
 0.92127919 0.71132845 0.39674256 0.32219388 0.01752252 0.80808931
 0.10068127 0.60769087 0.13527961 0.54884987]


In [36]:
# reshape() function returns a new arrays and a new objects and also convert one d-array into two d-array
D=C.reshape((4,4))
print((D))

[[0.14848473 0.97824624 0.26593814 0.84206382]
 [0.04942251 0.39308293 0.92127919 0.71132845]
 [0.39674256 0.32219388 0.01752252 0.80808931]
 [0.10068127 0.60769087 0.13527961 0.54884987]]


In [40]:
# to use shape attribute and it is also use to convert one d-array into two d-array
D.shape=(4,4)
print(D)

[[0.14848473 0.97824624 0.26593814 0.84206382]
 [0.04942251 0.39308293 0.92127919 0.71132845]
 [0.39674256 0.32219388 0.01752252 0.80808931]
 [0.10068127 0.60769087 0.13527961 0.54884987]]


In [42]:
# to use ravel() function to convert two d-array into one d-array
D=D.ravel()
print(D)

[0.14848473 0.97824624 0.26593814 0.84206382 0.04942251 0.39308293
 0.92127919 0.71132845 0.39674256 0.32219388 0.01752252 0.80808931
 0.10068127 0.60769087 0.13527961 0.54884987]


In [45]:
# use shape attribute directly on the array
D.shape=(16)
print(D)

[0.14848473 0.97824624 0.26593814 0.84206382 0.04942251 0.39308293
 0.92127919 0.71132845 0.39674256 0.32219388 0.01752252 0.80808931
 0.10068127 0.60769087 0.13527961 0.54884987]


In [55]:
# Transpose() function is use to convert rows into columns and columns into rows
C.transpose()


array([0.14848473, 0.97824624, 0.26593814, 0.84206382, 0.04942251,
       0.39308293, 0.92127919, 0.71132845, 0.39674256, 0.32219388,
       0.01752252, 0.80808931, 0.10068127, 0.60769087, 0.13527961,
       0.54884987])

In [54]:
B.transpose()


array([0.27402942, 0.66078788, 0.34532455, 0.571043  , 0.39601638,
       0.27276959, 0.53194231, 0.6940196 , 0.14721234, 0.43001565])

In [50]:
import numpy as np
E=np.random.random((25))
print(E)

[2.78998986e-01 7.21510166e-01 4.32738946e-01 1.72571130e-02
 8.88500173e-01 1.08677982e-01 4.31543037e-01 7.41740882e-01
 9.51016376e-01 2.33589733e-01 9.39651658e-01 6.92225919e-01
 2.46584417e-02 9.95978435e-01 3.58862563e-01 9.64238260e-01
 2.04689952e-01 3.89762097e-01 3.14069388e-01 5.12289633e-04
 1.88847245e-01 6.91450286e-01 5.53926023e-01 2.09280317e-01
 4.04922270e-01]


In [51]:
E.shape=(5,5)

In [52]:
print(E)

[[2.78998986e-01 7.21510166e-01 4.32738946e-01 1.72571130e-02
  8.88500173e-01]
 [1.08677982e-01 4.31543037e-01 7.41740882e-01 9.51016376e-01
  2.33589733e-01]
 [9.39651658e-01 6.92225919e-01 2.46584417e-02 9.95978435e-01
  3.58862563e-01]
 [9.64238260e-01 2.04689952e-01 3.89762097e-01 3.14069388e-01
  5.12289633e-04]
 [1.88847245e-01 6.91450286e-01 5.53926023e-01 2.09280317e-01
  4.04922270e-01]]


In [53]:
E.transpose()


array([[2.78998986e-01, 1.08677982e-01, 9.39651658e-01, 9.64238260e-01,
        1.88847245e-01],
       [7.21510166e-01, 4.31543037e-01, 6.92225919e-01, 2.04689952e-01,
        6.91450286e-01],
       [4.32738946e-01, 7.41740882e-01, 2.46584417e-02, 3.89762097e-01,
        5.53926023e-01],
       [1.72571130e-02, 9.51016376e-01, 9.95978435e-01, 3.14069388e-01,
        2.09280317e-01],
       [8.88500173e-01, 2.33589733e-01, 3.58862563e-01, 5.12289633e-04,
        4.04922270e-01]])

In [56]:
# Array manipulation
# joining two arrays
# merging two arrays
import numpy as np
a=np.ones((3,3))
b=np.zeros((3,3))
np.vstack((a,b))
# vstack() function is use to perform vertical stacking

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# hstack() function is use to perform horizontal stacking
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [58]:
# Another function column_stack() and row_stack() and it's functionality
import numpy as np
c=np.array([0,1,2])
d=np.array([3,4,5])
e=np.array([6,7,8])
np.column_stack((c,d,e))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [59]:
np.row_stack((c,d,e))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
# splitting arrays
import numpy as np
A=np.arange((16)).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
# if you want to split array into two parts horizontaly
[B,C]=np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [62]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [63]:
[B,C]=np.vsplit(A,2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
#TO split the array into many colums
[A1,A2,A3]=np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [68]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [69]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [70]:
# to split the array into many rows
[A1,A2,A3]=np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [71]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
A3

array([[12, 13, 14, 15]])

In [73]:
# Copies or views of objects
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [74]:
b=a
b

array([1, 2, 3, 4])

In [75]:
a[2]=5
b

array([1, 2, 5, 4])

In [78]:
import numpy as np
c=np.array([5,6,7,8,9])
c

array([5, 6, 7, 8, 9])

In [85]:
 d=c.copy()
d
# to use copy() function to copy one elements into other

array([ 5,  6,  7,  8, 10])

In [80]:
c[4]=10
c

array([ 5,  6,  7,  8, 10])

In [81]:
# to copy() function to copy one element into other
e=c.copy()
c

array([ 5,  6,  7,  8, 10])

In [82]:
e

array([ 5,  6,  7,  8, 10])

In [84]:
e=c[0:2]
e

array([5, 6])

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4], ndmin=5)

In [4]:
print(arr)

[[[[[1 2 3 4]]]]]


In [5]:
print("The dimension of the array:", arr.ndim)

The dimension of the array: 5


In [6]:
demo = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [7]:
print(demo)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [8]:
print(demo.ndim)

3


In [1]:
# fancy array is use to copy the data into a new array
import numpy as np
arr = np.empty((8,4))

In [3]:
for i in range(8):
    arr[i] = i

In [4]:
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [5]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [6]:
arr[[0,1,3,2,4]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.]])

In [9]:
# transposing arra
import numpy as np
arr1 = np.arange(15).reshape((3,5))

In [10]:
print(arr1)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
arr1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
arr2 = np.random.randn(6,3)

In [13]:
arr2

array([[ 0.47731691, -0.07168422,  0.80826542],
       [-0.01145039,  0.15455789, -2.32645673],
       [-1.41102256, -0.37799011,  1.20112329],
       [ 0.04873532, -1.66311064, -0.87720827],
       [-0.4186483 , -0.5431926 , -0.96900253],
       [ 0.05163517,  0.67111729,  0.15997916]])

In [17]:
arr1.swapaxes(1,1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])